### ISSUE TITLE
Engine parameters cannot be changed

### ISSUE THREAD

**Issue by wittmarf** [asdfjkl/jfxchess#136]
Hi,

I installed Jerry with snap on Kubuntu 22.10. Alternatively, I built it from source according to your instructions, which led to the same behavior as described below.

In the pop-up window, where the engines are listed, there is a button for editing the engine parameters. It is not active, cannot be clicked. This is the case for the built-in engine, as well as for newly installed engines. Those other engines can be used with Jerry btw, but just with one core since editing is not possible.

Any help appreciated, since Jerry really is a very nice chess GUI!

Kind regards,
Ralf

**Comment by asdfjkl** [comment]
I can reproduce this behavior; it's a bug.

**Comment by asdfjkl** [comment]
won't fix

- snap package will be released in such a way that users can add stockfish as long as it's installed in their home folder
- manual Linux installation or Windows installation will be able to anyway add Stockfish and edit the engine options to their liking
