### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by amchess** [asdfjkl/jfxchess#140]
Hi.
I am Andrea Manzo, the author of the ShashChess engine that I think you know.
That engine, with the related Shashin theory, opens new scenarios at gui level and I would like to make a "ShashGui"
I am co-owner of alpha-chess (www.alpha-chess.com), a sw house dealing with AI applied to chess.
We have a lot of innovative code, for now, mostly without gui.
I have seen this Jerry GUI and it looks very interesting.
I am a Java programmer for work and I know JavaFX.
We have a lot of java code that takes advantage of the new features of ShashChess.
The idea is to translate them into graphics to get a really original gui: shashin theory, experience file management, learning by positional features, live book, positional features, database reclamation, match commenting with our nlg sw, etc.
Would you like to collaborate?
Andrea

**Comment by asdfjkl** [comment]
Dear Andrea,

currently most my programming projects, including chess, are in maintenance mode - I simply can not afford the time for anything more ambitious. I wish you good luck with ShashChess!

- Dominik
