### ISSUE TITLE
lakinwecker: Touchscreen support

### ISSUE THREAD

**Issue by asdfjkl** [asdfjkl/jfxchess#16]
lakinwecker commented 3 hours ago
One of the things I find myself doing a lot is reading chessbooks on my surface pro, but none of the free or open source chess programs are terrible to use on a touchscreen. I'd like for there to be an option for Jerry to move the next/previous/first/last buttons closer to the edge of the screen and making them bigger so they are easier to press with your fingers.

Also, if supporting reading a chess book via jerry, we would need to find a spot to add in "next chapter" type buttons as well. I thought I would inquire about your interest in these features before I went about trying to implement them.

**Comment by asdfjkl** [comment]
first, cf the other comment - due to merging I had to delete your original comment; sorry.

1.) Touchscreen support - I think this is very important. 
Unfortunately I don't have a Surface Pro or similar device to test here. 
Ideally, there is only _one_ UI that caters _all_ audiences - think of the new Windows 10 Mail app, which is both usable by mouse and touch.
If that's impossible, there should be a "touchcreen" mode, that can be enabled via the GUI settings dialog (e.g. where one currently selects the style).

2.) Studying PDFs while using Jerry. This boils down to stacking all GUI elements row-wise to get one big column. Then there is space one the left side/and or right side of the screen to put adobe reader next to Jerry and display a PDF -> This is imho very important; like 99% of my chess books are PDF.

3.) I think what you call "chessbook" is probably a PGN structured in a certain way, like those sold by Everymanchess. I think these are important too, but way less than PDF.

If you want to work on any of these, go ahead. If you submit code, please make sure it's neat and clean :-) This makes it much easier to include in the main-line...

**Comment by lakinwecker** [comment]
I am referring to both PDFs and the PGN books that everyman chess distributes.  Both are worthwhile.  PGN books for opening repertoires which would integrate very nicely with the opening repertoire study that I referenced in the other ticket.

I also agree that we should support both with the same interface if possible.  I will endeavour to accomplish that when I work on it, but no promises at this point.

**Comment by asdfjkl** [comment]
... well this is apparently not going to happen...
